### ISSUE TITLE
I found a wrong place.

### ISSUE THREAD

**Issue by githubhanjunjun** [AnalyticalGraphicsInc/3d-tiles-tools#155]
Under the 3d-tiles-tools-master\samples-generator\lib\createTilesetJsonSingle.js path, Forty-sixth lines，
root:{content:{uri}}, It should be root:{content:{url}}

**Comment by likangning93** [comment]
Hi @githubhanjunjun, do you mean the use of `uri` here instead of `url`? Here's the line: https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/blob/master/samples-generator/lib/createTilesetJsonSingle.js#L46

`uri` is currently the correct method for linking to tile content in the 3D Tiles specification. See here: https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#tilecontenturi-white_check_mark
